version: "3"
services:
  mongo:
    container_name: mongo-container-api1
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: in-gaia-teste-api1-container
    build: .
    image: api1
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/api1/dist
      - ./package.json:/usr/src/api1/package.json
    ports: 
      - "3333:3333"
      - "9222:9222"
    links:
      - mongo