version: "3"
services:
  api:
    container_name: in-gaia-teste-api1-container
    image: node:14
    working_dir: /usr/src/api1
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist:/usr/src/api1/dist/
      - ./package.json:/usr/src/api1/package.json
    ports: 
      - "3333:3333"
      - "9222:9222"